# Generated by Django 4.1.7 on 2023-04-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telenet_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('service', models.ForeignKey(default='Undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='telenet_site.service')),
            ],
        ),
    ]
