# Generated by Django 4.1.7 on 2023-04-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telenet_site', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(default='Undefined', on_delete=django.db.models.deletion.CASCADE, to='telenet_site.service'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
