# Generated by Django 4.1.7 on 2023-04-06 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telenet_site', '0003_alter_feedback_service_alter_feedback_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
