# Generated by Django 4.1.7 on 2023-04-13 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telenet_site', '0004_feedback_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 13, 18, 50, 54, 254473, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='edit_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 4, 13, 18, 51, 2, 832474, tzinfo=datetime.timezone.utc), upload_to='feedback_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 4, 13, 18, 51, 10, 206474, tzinfo=datetime.timezone.utc), upload_to='service_images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('order_end_date', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='telenet_site.service')),
            ],
        ),
    ]
