# Generated by Django 4.1.7 on 2023-04-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telenet_site', '0005_feedback_create_datetime_feedback_edit_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='feedback_images/2023-04-14 00:11:59.858442'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service_images/2023-04-14 00:11:59.857439'),
        ),
    ]
